#!/usr/bin/env python3
"""WP13: all Paper-1 figures generated by fixed script from committed
artifacts (runs/m1, reports/). No hand-edited numbers.

Outputs: reports/figures/fig3_battery.png, fig4_headline.png,
fig5_gate_matrix.png, fig6_selection.png (+ .svg where useful).
Figs 1-2 (architecture/routing schematics) are drawn separately.
"""
import json
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "reports" / "figures"
OUT.mkdir(parents=True, exist_ok=True)


def _bundle(run):
    return json.loads((ROOT / "runs" / "m1" / run / "bundle.json").read_text())


def _obs(bundle, name):
    return next(o for o in bundle["observations"] if o["name"] == name)


def fig3_battery():
    fig, axes = plt.subplots(2, 3, figsize=(12, 7))

    b = _bundle("silicon_boundary")
    ax = axes[0, 0]
    for nm, style in [("kappa_baseline", "-"), ("kappa_intervention", "--")]:
        c = _obs(b, nm)["value"]
        ax.plot(c["x"], c["y"], style, label=nm.replace("kappa_", "L "))
    ax.set_xscale("log"); ax.set_yscale("log")
    ax.set_xlabel("T (K)"); ax.set_ylabel(r"$\kappa$ (W/m/K)")
    ax.set_title("Callaway Si boundary intervention"); ax.legend(fontsize=7)

    b = _bundle("si_eos")
    c = _obs(b, "E_V_curve")["value"]
    B0 = _obs(b, "B0")["value"]
    ax = axes[0, 1]
    ax.plot(c["x"], c["y"], "o-", ms=3)
    ax.set_xlabel(r"V (Å$^3$/cell)"); ax.set_ylabel("E (eV/cell)")
    ax.set_title(f"SW-Si EOS: B0 = {B0['value']:.1f} GPa")

    b = _bundle("si_elastic")
    ax = axes[0, 2]
    names = ["C11", "C12", "C44"]
    vals = [_obs(b, n)["value"]["value"] for n in names]
    ax.bar(names, vals, color=["tab:blue"] * 3)
    ax.set_ylabel("GPa"); ax.set_title("SW-Si elastic constants (relaxed-ion)")
    for i, v in enumerate(vals):
        ax.text(i, v + 2, f"{v:.1f}", ha="center", fontsize=8)

    b = _bundle("si_expansion")
    c = _obs(b, "a_vs_T")["value"]
    al = _obs(b, "alpha_linear")["value"]
    ax = axes[1, 0]
    ax.plot(c["x"], c["y"], "s-")
    ax.set_xlabel("T (K)"); ax.set_ylabel(r"a (Å)")
    ax.set_title(f"SW-Si NPT: alpha = {al['value']:.2e}/K")

    b = _bundle("lj_diffusion")
    c = _obs(b, "msd_vs_t")["value"]
    D = _obs(b, "D_star")["value"]
    ax = axes[1, 1]
    ax.plot(c["x"], c["y"], ".-")
    ax.set_xlabel("t*"); ax.set_ylabel("MSD*")
    ax.set_title(f"LJ liquid MSD: D* = {D['value']:.3f}")

    b = _bundle("lj_kappa_gk")
    k = _obs(b, "kappa_star")["value"]
    diag = json.loads((ROOT / "runs" / "m1" / "lj_kappa_gk" /
                       "raw" / "raw_outputs.json").read_text())["gk"]
    ax = axes[1, 2]
    comps = [diag["k11_lj"], diag["k22_lj"], diag["k33_lj"]]
    ax.bar(["k11", "k22", "k33"], comps, color="tab:orange")
    ax.axhline(k["value"], ls="--", c="k", lw=1)
    ax.set_ylabel(r"$\kappa$*")
    ax.set_title(f"LJ Green-Kubo: mean = {k['value']:.2f}")

    fig.suptitle("Benchmark battery — six capabilities, four property "
                 "families, two engines (sandbox runs)", fontsize=11)
    fig.tight_layout()
    fig.savefig(OUT / "fig3_battery.png", dpi=150)
    plt.close(fig)


def fig4_headline():
    m = json.loads((ROOT / "reports" / "battery" / "pilot_callaway" /
                    "battery_metrics.json").read_text())["metrics"]
    b = m["silicon_boundary"]
    labels = ["Recovery\n(clean, gates ON)",
              "Unflagged false claims\n(corrupted, gates ON)",
              "Unflagged false claims\n(corrupted, gates OFF)"]
    keys = ["recovery", "unflagged_false_claims_gates_on",
            "unflagged_false_claims_gates_off"]
    ps, los, his = [], [], []
    for k in keys:
        p, lo, hi = b[k]["wilson95"]
        ps.append(p); los.append(p - lo); his.append(hi - p)
    fig, ax = plt.subplots(figsize=(6.5, 4.5))
    colors = ["tab:green", "tab:green", "tab:red"]
    ax.bar(labels, ps, yerr=[los, his], capsize=6, color=colors, alpha=0.85)
    ax.set_ylabel("rate (Wilson 95% CI)")
    ax.set_ylim(0, 1.05)
    ax.set_title(f"Gate ablation, Callaway benchmark — PILOT N = "
                 f"{b['n_seeds']} (pre-registered N = 30 on CARC pending)")
    fig.tight_layout()
    fig.savefig(OUT / "fig4_headline.png", dpi=150)
    plt.close(fig)


def fig5_gate_matrix():
    data = json.loads((ROOT / "reports" / "gate_matrix" /
                       "gate_matrix.json").read_text())
    rows = data["rows"]
    labels = [f"{r['kind']}:{r['corruption']}" for r in rows]
    fig, ax = plt.subplots(figsize=(7, 8))
    det = [1 if r["detected_by_intended"] else 0 for r in rows]
    col = [len(r["collateral_gates"]) for r in rows]
    y = np.arange(len(rows))
    ax.barh(y, det, color="tab:green", label="intended gate fired")
    ax.barh(y, [-c for c in col], color="tab:red", label="collateral failures")
    ax.set_yticks(y); ax.set_yticklabels(labels, fontsize=7)
    ax.set_xlim(-2, 1.4); ax.set_xticks([-2, -1, 0, 1])
    ax.axvline(0, c="k", lw=0.5)
    ax.set_title(f"Gate matrix: sensitivity {data['sensitivity']:.0%}, "
                 f"selectivity {data['selectivity']:.0%} "
                 f"({data['n_pairs']} pairs)")
    ax.legend(fontsize=8, loc="lower right")
    fig.tight_layout()
    fig.savefig(OUT / "fig5_gate_matrix.png", dpi=150)
    plt.close(fig)


def fig6_selection():
    data = json.loads((ROOT / "reports" / "selection_baseline" /
                       "selection_metrics.json").read_text())["results"]
    arms = list(data)
    cov = [data[a]["mean"]["family_coverage"] for a in arms]
    cpf = [data[a]["mean"]["cost_per_family_s"] for a in arms]
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(9, 4))
    a1.bar(arms, cov, color="tab:blue"); a1.set_ylim(0, 1)
    a1.set_ylabel("property-family coverage"); a1.set_title("Coverage (K=4 slots)")
    a2.bar(arms, cpf, color="tab:purple")
    a2.set_ylabel("cost per family (s)"); a2.set_title("Efficiency")
    fig.suptitle("Experiment-selection baselines (LLM arm pending API key)")
    fig.tight_layout()
    fig.savefig(OUT / "fig6_selection.png", dpi=150)
    plt.close(fig)


if __name__ == "__main__":
    fig3_battery()
    fig4_headline()
    fig5_gate_matrix()
    fig6_selection()
    print(f"figures -> {OUT}")
    sys.exit(0)
